name: Tests

on:
  push:
    branches: [ main, develop, feat/documentation ]
  pull_request:
    branches: [ main, develop, feat/documentation ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Conda channels
        run: |
          conda config --add channels salilab
          conda config --add channels conda-forge
          conda config --add channels defaults

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: requirements.yml
          activate-environment: fepa_env
          auto-update-conda: true
          use-mamba: true

      - name: Install package in editable mode
        run: |
          pip install --no-cache-dir -e .

      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings
