name: Tests

on:
  push:
    branches: [ main, develop, feat/documentation ]
  pull_request:
    branches: [ main, develop, feat/documentation ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: requirements.yml  # ðŸ‘ˆ your Conda env file
          activate-environment: fepa_env      # ðŸ‘ˆ env name from the yml
          python-version: 3.10                # ðŸ‘ˆ matches your pyproject.toml

      - name: Install editable package
        run: |
          pip install --no-cache-dir -e .

      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings

