name: Tests

on:
  push:
    branches: [ main, develop, feat/documentation ]
  pull_request:
    branches: [ main, develop, feat/documentation ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          activate-environment: fepa_env
          environment-file: requirements.yml
          auto-update-conda: true

      - name: Configure Conda channels
        run: |
          conda config --add channels salilab
          conda config --add channels conda-forge
          conda config --add channels defaults

      - name: Install editable package
        run: |
          pip install --no-cache-dir -e .

      - name: Run tests
        run: |
          pytest -v --maxfail=1 --disable-warnings


